### ISSUE TITLE
[BUG BASH] Resolve bugs identified during Milestones #1 and #2

### ISSUE THREAD

**Issue by Poggecci** [uprm-inso4116-2023-2024-S1/semester-project-college-toolbox#243]
# Bugs Resolved
- [x] When viewing the page from Github Pages, the code to check if you are logged in does not properly detect the auth token cookie. Solved with
- [x] When a section is asynchronous or has no schedule data, conversion to the API representation of a schedule containing that section fails. Solved with
- [x] Current Time is blocked by section schedules at that time on the UI. Solved with
- [x] Register endpoint throwing a 500 despite successfully registering users. Solved with
- [x] Prod frontend deployments failing after recent merge. Solved with
